// <auto-generated />
using System;
using BackEndMediClock.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEndMediClock.Migrations
{
    [DbContext(typeof(MediClockDbContext))]
    partial class MediClockDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackEndMediClock.Models.Alarma", b =>
                {
                    b.Property<int>("AlarmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlarmaId"));

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<int>("DispositivoId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("time");

                    b.Property<int>("NumeroAlarma")
                        .HasColumnType("int");

                    b.HasKey("AlarmaId");

                    b.HasIndex("DispositivoId", "DiaSemana", "NumeroAlarma")
                        .IsUnique();

                    b.ToTable("Alarmas");
                });

            modelBuilder.Entity("BackEndMediClock.Models.Dispositivo", b =>
                {
                    b.Property<int>("DispositivoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DispositivoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DispositivoId");

                    b.ToTable("Dispositivos");
                });

            modelBuilder.Entity("BackEndMediClock.Models.Evento", b =>
                {
                    b.Property<int>("EventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventoId"));

                    b.Property<int?>("AlarmaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("DispositivoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("EventoId");

                    b.HasIndex("AlarmaId");

                    b.HasIndex("DispositivoId");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("BackEndMediClock.Models.Alarma", b =>
                {
                    b.HasOne("BackEndMediClock.Models.Dispositivo", "Dispositivo")
                        .WithMany("Alarmas")
                        .HasForeignKey("DispositivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dispositivo");
                });

            modelBuilder.Entity("BackEndMediClock.Models.Evento", b =>
                {
                    b.HasOne("BackEndMediClock.Models.Alarma", "Alarma")
                        .WithMany("Eventos")
                        .HasForeignKey("AlarmaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BackEndMediClock.Models.Dispositivo", "Dispositivo")
                        .WithMany("Eventos")
                        .HasForeignKey("DispositivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alarma");

                    b.Navigation("Dispositivo");
                });

            modelBuilder.Entity("BackEndMediClock.Models.Alarma", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("BackEndMediClock.Models.Dispositivo", b =>
                {
                    b.Navigation("Alarmas");

                    b.Navigation("Eventos");
                });
#pragma warning restore 612, 618
        }
    }
}
